version: 2.1
jobs:

  retrieve_sbt:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Retrieve sbt
          command: sbt update
      - save_cache:
          key: v1
          paths:
            - ~/.iv2/cache/
            - ~/.sbt/

  ensure_formatting:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1
      - run:
          name: Check that files are formatted properly
          command: cat /dev/null | sbt scalafmtSbtCheck

  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Ensure that dependencies are up-to-date
          command: cat /dev/null | sbt dependencyUpdatesFailBuild

      - run:
          name: Run Sonar code analysis
          command: cat /dev/null | sbt sonarScan

      - run:
          name: Compile
          command: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: Run tests
          command: cat /dev/null | sbt test:test

workflows:
  version: 2.1
  test:
    jobs:
      - retrieve_sbt
      - ensure_formatting:
          requires:
            - retrieve_sbt